# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='a_status',
            field=models.ForeignKey(default='Published', on_delete=django.db.models.deletion.CASCADE, to='books.Status'),
        ),
    ]
