jobs:
  build-python2:
    working_directory: ~/pathagar
    docker:
      - image: circleci/python:2.7.14
      - image: circleci/postgres:9.6.2
    steps:
      - checkout
      - restore_cache:
          key: v1-python2-{{ checksum "requirements.txt" }}
      - run:
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: v1-python2-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            python manage.py test
  build-python3:
    working_directory: ~/pathagar
    docker:
      - image: circleci/python:3.5.3
      - image: circleci/postgres:9.6.2
    steps:
      - checkout
      - restore_cache:
          key: v1-python3-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: v1-python3-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            python manage.py test
      - store_artifacts:
          path: test-reports/
          destination: tr1

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-python2
      - build-python3
